In [163]:
import numpy as np

In [164]:
# Input matrix: A - matrix of size n x n
A = np.array([
    [10, 2, 3, 4, 5],
    [2, 20, 6, 7, 8],
    [3, 6, 30, 9, 10],
    [4, 7, 9, 40, 11],
    [5, 8, 10, 11, 50]
])

In [165]:
def MaxEigenvalue(A, eps=1e-6):
    n = A.shape[0]
    x0 = []
    for _ in range(n): x0.append(1)
    x0 = np.array(x0)

    x = A @ x0
    print('x =', x)

    m = np.random.randint(0, n)
    print('m =', m)

    lambda0 = x[m] / x0[m]
    print('lambda0 =', lambda0)

    if lambda0 > 1:
        x_norm2 = np.linalg.norm(x, ord=2)
        print('x_norm =', x_norm2)
    else:
        x_norm2 = 1

    e = x / x_norm2
    print('e =', e)

    while True:
        print('-----------------------------------------------------')
        x = A @ e
        print('x =', x)

        lambda1 = x[m] / e[m]
        print('lambda1 =', lambda1)

        if abs(lambda1 - lambda0) < eps:
            return lambda1

        lambda0 = lambda1
        if lambda0 > 1:
            x_norm2 = np.linalg.norm(x, ord=2)
            print('x_norm =', x_norm2)
        else:
            x_norm2 = 1

        e = x / x_norm2
        print('e =', e)

B = np.array([
    [2, 1, 0],
    [1, 2, 1],
    [0, 1, 2]
])

# Test
val = MaxEigenvalue(B, eps=0.5)
assert abs(val - 3.333333333333333) < 0.00001


x = [3 4 3]
m = 0
lambda0 = 3.0
x_norm = 5.830951894845301
e = [0.51449576 0.68599434 0.51449576]
-----------------------------------------------------
x = [1.71498585 2.40098019 1.71498585]
lambda1 = 3.3333333333333335


In [166]:
def CheckPositive(A):
    n = A.shape[0]
    for i in range(n):
        if np.linalg.det(A[:i, :i]) < 0:
            return False
    return True

def CheckSymmetric(A):
    return np.allclose(A, A.T)

In [167]:
def MinEigenvalue(A, eps=1e-6):
    if not CheckPositive(A):
        print('Matrix is not positive')
        return None
    if not CheckSymmetric(A):
        print('Matrix is not symmetric')
        return None

    # matrix is symmetric so we can use 1-norm instead of inf-norm
    A_norm = np.linalg.norm(A, ord=1)
    print('A_norm =', A_norm)

    B = A_norm * np.eye(A.shape[0]) - A
    print('B =', B)

    B_max_eigenvalue = MaxEigenvalue(B, eps=eps)
    print('B_max_eigenvalue =', B_max_eigenvalue)

    return A_norm - B_max_eigenvalue

B = np.array([
    [2, -1, 0],
    [-1, 2, -1],
    [0, -1, 2]
])

# Test
val = MinEigenvalue(B, eps=0.5)
assert abs(val - 0.6666666666666665) < 0.0000001



A_norm = 4.0
B = [[2. 1. 0.]
 [1. 2. 1.]
 [0. 1. 2.]]
x = [3. 4. 3.]
m = 2
lambda0 = 3.0
x_norm = 5.830951894845301
e = [0.51449576 0.68599434 0.51449576]
-----------------------------------------------------
x = [1.71498585 2.40098019 1.71498585]
lambda1 = 3.3333333333333335
B_max_eigenvalue = 3.3333333333333335


In [168]:
print('Max eigenvalue:', MaxEigenvalue(A))

x = [24 43 58 71 84]
m = 1
lambda0 = 43.0
x_norm = 133.7385509118444
e = [0.17945461 0.32152285 0.43368198 0.53088657 0.62809115]
-----------------------------------------------------
x = [ 9.00263979 18.13239327 26.53685101 35.01608151 45.05058533]
lambda1 = 56.3953488372093
x_norm = 66.10383403050363
e = [0.13618937 0.27430169 0.40144193 0.52971332 0.68151244]
-----------------------------------------------------
x = [ 8.64123842 17.3271569  25.6801806  34.76301646 46.79224834]
lambda1 = 63.168247422680416
x_norm = 66.57593305096513
e = [0.12979523 0.26026157 0.38572769 0.5221559  0.70284029]
-----------------------------------------------------
x = [ 8.57848356 17.05700166 25.25059176 34.43004044 47.47407519]
lambda1 = 65.5379186985501
x_norm = 66.64337603872923
e = [0.12872222 0.25594444 0.37889125 0.5166311  0.71236   ]
-----------------------------------------------------
x = [ 8.56410923 16.96497841 25.06185053 34.21772503 47.78102104]
lambda1 = 66.283832181443
x_norm = 66.65680

In [169]:
print('Min eigenvalue:', MinEigenvalue(A))

A_norm = 84.0
B = [[ 74.  -2.  -3.  -4.  -5.]
 [ -2.  64.  -6.  -7.  -8.]
 [ -3.  -6.  54.  -9. -10.]
 [ -4.  -7.  -9.  44. -11.]
 [ -5.  -8. -10. -11.  34.]]
x = [60. 41. 26. 13.  0.]
m = 3
lambda0 = 13.0
x_norm = 78.26876771739798
e = [0.7665893  0.52383602 0.3321887  0.16609435 0.        ]
-----------------------------------------------------
x = [ 54.0189928   28.83653424  11.00055648  -2.4147563  -13.1725595 ]
lambda1 = -14.538461538461537
x_norm = 63.63927171955303
e = [ 0.8488311   0.45312483  0.17285799 -0.03794444 -0.2069879 ]
-----------------------------------------------------
x = [ 62.57539479  28.18669335   6.48046806  -7.51560835 -16.21793397]
lambda1 = 198.06878306878306
x_norm = 71.21567196033048
e = [ 0.8786745   0.39579341  0.09099778 -0.10553307 -0.22772985]
-----------------------------------------------------
x = [ 65.51811418  25.58801253   3.13019227  -9.24265854 -15.05164853]
lambda1 = 87.58068652330705
x_norm = 72.58888782318336
e = [ 0.90259151  0.35250592  0